[project]
name = "move-tracker"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.5",
    "numpy>=1.20",
    "openpyxl==3.1.4",
    "pandas>=2.0",
    "rich>=12.0",
    "typer>=0.9.0",
    "uv>=0.7.19",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
